### PR TITLE
Update garner spark version

### PR DESCRIPTION
**Pull request by eric-pham**
Update garner spark function to match the version of BA that I am going to merge

### CODE REVIEW

**Comment by eric-pham** [comment]
https://github.com/GarnerCorp/business-analytics/pull/74

**Review by bgolding355 — APPROVED** [review]

**Comment by vmandrychenko** [comment]
@eric-pham what's up with this PR?

**Comment by eric-pham** [comment]
> @eric-pham what's up with this PR? 

The garner auth and spark functions should match the version that BA is on

**Comment by vmandrychenko** [comment]
> > @eric-pham what's up with this PR?
> 
> The garner auth and spark functions should match the version that BA is on

This is going to require full retest to make sure there are no lib clashes? Do we need to bump other libraries?

**Pull request merged**
